version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
      timezone: "America/Chihuahua"
    open-pull-requests-limit: 5
    reviewers: ["cetinajero"]
    labels:
      - dependencies
      - ruby
