title: popcorntime-dl
url: cetinajero.github.io/popcorntime-dl
theme:

api:
  popcorntime:
    cors-proxy: https://cors-anywhere.herokuapp.com
    server:  https://popcorn-time.ga # /movies/1?keywords=shawshank
    types: |
      ['movies', 'shows']
  yify:
    host: https://yts-subs.com
    uri:
      movies: /movie-imdb/${item.imdb_id}

exclude: ["docs", "Gemfile", "Gemfile.lock", "LICENSE", "Rakefile", "README.md"]
