title: popcorntime-dl
url: cetinajero.github.io/popcorntime-dl

api:
  popcorntime:
    host: https://tv-v2.api-fetch.website
    types: |
      ['movies', 'shows']
  yify:
    host: https://www.yifysubtitles.com
    uri:
      movies: /movie-imdb/${item.imdb_id}
