title: popcorntime-dl
url: cetinajero.github.io/popcorntime-dl
theme:

api:
  popcorntime:
    host: https://tv-v2.api-fetch.website
    types: |
      ['movies', 'shows']
  yify:
    host: https://www.yifysubtitles.com
    uri:
      movies: /movie-imdb/${item.imdb_id}

exclude: ["docs", "Gemfile", "Gemfile.lock", "LICENSE", "Rakefile", "README.md"]
