title: popcorntime-dl
url: cetinajero.github.io/popcorntime-dl
theme:

api:
  popcorntime:
    host: https://cors-anywhere.herokuapp.com/https://tv-v2.api-fetch.sh
    types: |
      ['movies', 'shows']
  yify:
    host: https://yts-subs.com
    uri:
      movies: /movie-imdb/${item.imdb_id}

exclude: ["docs", "Gemfile", "Gemfile.lock", "LICENSE", "Rakefile", "README.md"]
