title: popcorntime-dl
url: cetinajero.github.io/popcorntime-dl

api:
  popcorntime:
    host: https://tv-v2.api-fetch.website
    uri:
      movies: /movies/1?keywords=${query}
  yify:
    host: https://www.yifysubtitles.com
    uri:
      movies: /movie-imdb/${item.imdb_id}
